package com.example.core.enums;

public enum PositionsTabColumnsEnum {
	QUANTITY,
	LAST_PRICE_PRICE,
	LAST_PRICE_CHANGE,
	CURRENT_VALUE,
	TODAYS_CHANGE_DOLLAR,
	TODAYS_CHANGE_PERCENT,
	TOTAL_CHANGE_DOLLAR,
	TOTAL_CHANGE_PERCENT,
	COST_BASIS_PER_SHARE,
	COST_BASIS_TOTAL

}
