FROM ubuntu:16.04
MAINTAINER Lukasz Stefaniszyn "lukasz.stefaniszyn@capgemini.com"

LABEL name=ubuntu_java \
            version=v1-8.0 \
            base="ubuntu:16.04" \
            build_date="03-11-2017" \
            java="1.8" \
            maven="3.3.9" \
            ant="1.9.9" \
            sonar_scanner="3.0.3" \
            udeploy_client="" \
            description="This basic docker to use in java and maven dev env."

# Update and install needed applications
COPY 80proxy /etc/apt/apt.conf.d/80proxy
RUN apt-get update
RUN apt-get install -y \
            wget \
            libfontconfig \
            unzip \
            zip \
            ksh \
            curl \
            git

COPY wgetrc /etc/wgetrc

#Env parameters
ENV M2_HOME=/opt/apache-maven-3.3.9
ENV M2=$M2_HOME/bin/
ENV ANT_HOME=/opt/apache-ant-1.9.9
ENV ANT=$ANT_HOME/bin/


### JAVA PART ###
#TO UPDATE:  please verify url link to JDK http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
## Download and install Java JDK8
RUN mkdir /opt/jdk
RUN wget -qq --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz && tar -zxf jdk-8u161-linux-x64.tar.gz -C /opt/jdk && rm jdk-8u161-linux-x64.tar.gz && update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_161/bin/java 100 && update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_161/bin/javac 100 && java -version && chmod 755 -R /opt/jdk/jdk1.8.0_161/

RUN java -version

RUN wget -q http://mirror.cogentco.com/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz && tar xzf apache-maven-3.3.9-bin.tar.gz -C /opt && rm apache-maven-3.3.9-bin.tar.gz && ln -s /opt/apache-maven-3.3.9/bin/mvn /usr/bin/mvn && mvn --version && chmod 755 -R /opt/apache-maven-3.3.9/

## Install sonar runner
RUN wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip && unzip -qq sonar-scanner-cli-3.0.3.778-linux.zip -d /opt/ && rm sonar-scanner-cli-3.0.3.778-linux.zip  && ln -s /opt/sonar-scanner-3.0.3.778-linux/bin/sonar-scanner /usr/bin/sonar-scanner && sonar-scanner --version && chmod 755 -R /opt/sonar-scanner-3.0.3.778-linux/

## COPY Maven setting.xml file
COPY settings.xml /opt/apache-maven-3.3.9/conf/settings.xml

## Install dependencies
RUN mkdir /opt/tmp
COPY pom.xml /opt/tmp
RUN mkdir /usr/share/maven2 && chmod 777 -R /usr/share/maven2
RUN cd /opt/tmp && mvn clean; exit 0
RUN cd /opt/tmp && mvn install -e -DskipTests=true; exit 0
RUN cd /opt/tmp && mvn test -DskipTests=true; exit 0
RUN cd /opt/tmp && mvn site -DskipTests=true; exit 0
RUN chmod 777 -R /usr/share/maven2
RUN chmod 755 /usr/bin/java && chmod 755 /usr/bin/mvn

## Create app folder
RUN mkdir -p -m 777 /app
RUN useradd -u 29001 -g 100 eeuser
WORKDIR /app
