package com.capgemini.mrchecker.test.core.testRunners;

import org.junit.runner.RunWith;

import com.googlecode.junittoolbox.SuiteClasses;

@RunWith(ParallelTestClassRunner.class)
@SuiteClasses("**/autogenerated_runners/*.class")
public class RunCucumberTestSuite {
}