= What is Selenium

Selenium is a framework for testing browser applications. The test automation supports:

* Frequent regression testing
* Repeating test case executions
* Documentation of test cases
* Finding defects
* Multiple Browsers

The Selenium testing framework consists of multiple tools:

* *Selenium IDE*
+
The Selenium Integrated Development Environment is a prototyping tool for building test scripts. It is a Firefox Plugin and provides an easy-to-use interface for developing test cases. Additionally, Selenium IDE contains a recording feature, that allows the user to record user inputs that can be automatically re-executed in future.
+
* *Selenium 1*
+
Selenium 1, also known as Selenium RC, commands a Selenium Server to launch and kill browsers, interpreting the Selenese commands passed from the test program. The Server acts as an HTTP proxy. *This tool is deprecated*.
+
* *Selenium 2*
+
Selenium 2, also known as Selenium WebDriver, is designed to supply a well-designed, object-oriented API that provides improved support for modern advanced web-app testing problems.
+
* *Selenium 3.0*
+
The major change in Selenium 3.0 is removing the original Selenium Core implementation and replacing it with one backed by WebDriver. There is now a W3C specification for browser automation, based on the Open Source WebDriver.
+
* *Selenium Grid*
+
Selenium Grid allows the scaling of Selenium RC test cases, that must be run in multiple and potentially variable environments. The tests can be run in parallel on different remote machines.

== Selenium on the Production Line

More information on Selenium on the Production Line can be found https://km3.capgemini.com/book/1051672[here].

*tl;dr*

The Production Line has containers running Chrome and Firefox Selenium Nodes. The communication with these nodes is accomplished using Selenium Grid.

Having issues using Selenium on the Production Line? Check the Production Line https://km3.capgemini.com/book/1074416[issue list], maybe it’s a known issue that can be worked around.
