// Generated by GraphWalker (http://www.graphwalker.org)
package graphs;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "graphs/SampleGraph.json")
public interface SampleGraph {

    @Vertex()
    void v_Stage2();

    @Vertex()
    void v_Stage1();

    @Vertex()
    void v_Stage3();

    @Vertex()
    void v_End();

    @Edge()
    void e_apply();

    @Vertex()
    void v_Start();

    @Edge()
    void e_initialize();

    @Edge()
    void e_create();

    @Edge()
    void e_finish();

    @Edge()
    void e_remove();
}
