package com.example.selenium.tests.cucumber;

import org.junit.runner.RunWith;

import com.googlecode.junittoolbox.SuiteClasses;

@RunWith(ParallelSuite.class)
@SuiteClasses("**/autogenerated_runners/*.class")
public class RunCucumberTestSuite {
}