= Chromedriver version is not compatible with Chrome browser

*Problem:*

During the tests your web browser window opens and immediately closes, all your tests are broken.

Following error message is visible in the test description: 

----
session not created: This version of ChromeDriver only supports Chrome version 76
Build info: version: '<build_version>', revision: '<build_revision>', time: '<time>'
System info: host: '<your_computer_name>', ip: '<your_ip_address>', os.name: '<your_os_name>', os.arch: '<your_os_architecture>', os.version: '<your_os_version>', java.version: '<java_version_installed>'
Driver info: driver.version: NewChromeDriver
----

*Solution:* 

1. Make a change in the following files:
    * `MrChecker_Test_Framework\workspace\devonfw-testing\src\resources\settings.properties`
    * For project template-app-under-test: `MrChecker_Test_Framework\workspace\devonfw-testing\template\src\resources\settings.properties`
    * For project example-app-under-test: `MrChecker_Test_Framework\workspace\devonfw-testing\example\src\resources\settings.properties`
+
Change the value of `selenium.driverAutoUpdate` field form `true` to `false`

2. Replace the following file with a version compatible with your browser:  
`MrChecker_Test_Framework\workspace\devonfw-testing\example\lib\webdrivers\chrome\chromedriver.exe` .
