:toc: macro

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]
:idprefix:
:idseparator: -
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing
 
 
= Who is MrChecker?

MrChecker Test Framework is an end to end test automation framework written in Java.
It is an automated testing framework for functional testing of web applications, API web services, Service Virtualization, Security, native mobile apps and in coming future databases. All modules have tangible examples of how to build resilient integration test cases based on delivered functions. 

= Where MrChecker applies?

The main goal of MrChecker is to standardize the way we build BlackBox tests. It gives the possibility to have one common software standard in order to build: Component, Integration and System tests.

A Test Engineer does not have access to the application source code in order to perform BlackBox tests, but he is able to attach his tests to any application interfaces, such as  - IP address - Domain Name - communication protocol - Command Line Interface.

= MrChecker’s specification:

* Responsive Web Design application: Selenium Browser

* REST/SOAP: RestAssure

* Service Virtualization: Wiremock

* Database: JDBC drivers for SQL

* Security: RestAssure + RestAssure Security lib

* Standalone Java application: SWING

* Native mobile application for Android: Appium

